/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm.view;

import javax.swing.JLabel;

/**
 *
 * @author student
 */
public class PanelMenu extends javax.swing.JPanel {

    public PanelMenu() {
        initComponents();
        clear();
    }

    public JLabel getLabel1() {
        return label1;
    }

    public JLabel getLabel2() {
        return label2;
    }

    public JLabel getLabel3() {
        return label3;
    }

    public JLabel getLabel4() {
        return label4;
    }

    public JLabel getLabel5() {
        return label5;
    }

    public JLabel getLabel6() {
        return label6;
    }

    public JLabel getLabel7() {
        return label7;
    }

    public JLabel getLabel8() {
        return label8;
    }

    public JLabel getLabelJudul() {
        return labelJudul;
    }
    
    public void clear() {
        label1.setText("");
        label2.setText("");
        label3.setText("");
        label4.setText("");
        label5.setText("");
        label6.setText("");
        label7.setText("");
        label8.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelJudul = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 255));

        labelJudul.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelJudul.setForeground(new java.awt.Color(255, 255, 0));
        labelJudul.setText("ATM PENS");

        label8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label8.setForeground(new java.awt.Color(255, 255, 0));
        label8.setText("Label8 -->");

        label7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 0));
        label7.setText("Label7 -->");

        label5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 0));
        label5.setText("Label5 -->");

        label6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 0));
        label6.setText("Label6 -->");

        label2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 0));
        label2.setText("<-- Label2");

        label3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 0));
        label3.setText("<-- Label3");

        label4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 0));
        label4.setText("<-- Label4");

        label1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 0));
        label1.setText("<-- Label1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label5, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(labelJudul)
                .addGap(0, 197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label5)
                    .addComponent(label1))
                .addGap(32, 32, 32)
                .addComponent(labelJudul)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label6)
                    .addComponent(label2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label7)
                    .addComponent(label3))
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label8)
                    .addComponent(label4))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel labelJudul;
    // End of variables declaration//GEN-END:variables
}
