/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm.view;

/**
 *
 * @author student
 */
public class PanelInfo extends javax.swing.JPanel {

    /**
     * Creates new form PanelLogin
     */
    public PanelInfo() {
        initComponents();
    }
    
    public void setJudul(String text) {
        judul.setText(text);
    }
    
    public void setInfo(String text) {
        info.setText(text);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label8 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 255));

        label8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label8.setForeground(new java.awt.Color(255, 255, 0));
        label8.setText("Keluar -->");

        label4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 0));
        label4.setText("<-- Kembali");

        info.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        info.setForeground(new java.awt.Color(255, 255, 0));
        info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info.setText("Rp. xxxxx");

        judul.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 0));
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("Judul");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                        .addComponent(label8))
                    .addComponent(info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addComponent(info)
                .addGap(176, 176, 176)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label8)
                    .addComponent(label4))
                .addGap(29, 29, 29))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(judul)
                    .addContainerGap(414, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel info;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label8;
    // End of variables declaration//GEN-END:variables
}
