/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm.view;

import javax.swing.JLabel;
import model.Database;
import model.Tabungan;

/**
 *
 * @author student
 */
public class PanelKonfirmasi extends javax.swing.JPanel {

    /**
     * Creates new form PanelLogin
     */
    public PanelKonfirmasi() {
        initComponents();
        clear();
    }

    public JLabel getInfo1() {
        return info1;
    }

    public JLabel getInfo2() {
        return info2;
    }

    public JLabel getInfo3() {
        return info3;
    }

    public JLabel getInfo4() {
        return info4;
    }
    
    

    public JLabel getJudul() {
        return judul;
    }
    
    public void clear() {
        judul.setText("");
        info1.setText("");
        info2.setText("");
        info3.setText("");
        info4.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        info2 = new javax.swing.JLabel();
        info1 = new javax.swing.JLabel();
        info3 = new javax.swing.JLabel();
        info4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 255));

        judul.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 0));
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("Judul");

        label8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label8.setForeground(new java.awt.Color(255, 255, 0));
        label8.setText("Tidak -->");

        label7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 0));
        label7.setText("Ya -->");

        label4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 0));
        label4.setText("<-- Kembali");

        info2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        info2.setForeground(new java.awt.Color(255, 255, 0));
        info2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        info2.setText("Info 2");

        info1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        info1.setForeground(new java.awt.Color(255, 255, 0));
        info1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        info1.setText("Info 1");

        info3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        info3.setForeground(new java.awt.Color(255, 255, 0));
        info3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        info3.setText("Info 3");

        info4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        info4.setForeground(new java.awt.Color(255, 255, 0));
        info4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        info4.setText("Info 4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                        .addComponent(label8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label7))
                    .addComponent(info2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(info3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(info1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(info4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(info1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info4)
                .addGap(44, 44, 44)
                .addComponent(label7)
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label8)
                    .addComponent(label4))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel info1;
    private javax.swing.JLabel info2;
    private javax.swing.JLabel info3;
    private javax.swing.JLabel info4;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    // End of variables declaration//GEN-END:variables
}
