/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobile.view;

import javax.swing.JPanel;
import launcher.Perbankan;

/**
 *
 * @author Ahmad Faiz Kamaludin
 */
public class Mobile extends javax.swing.JFrame {

    private JPanel main = new PanelMain(this);
    private Perbankan launcher;
    
    public Mobile(Perbankan launcher) {
        initComponents();
        this.launcher = launcher;
        this.setSize(400, 600);
        this.add(main);
        main.setVisible(true);
    }
    
    public void logOut() {
        this.dispose();
        launcher.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Mobile Banking");
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
