/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobile.view;

import javax.swing.JPanel;
import mobile.controller.MobileController;

/**
 *
 * @author Ahmad Faiz Kamaludin
 */
public class PanelMain extends JPanel {

    private JPanel beranda = new PanelBeranda(this);
    private JPanel informasi = new PanelInformasi();
    private JPanel transfer = new PanelTransfer();
    private JPanel pembayaran = new PanelPembayaran();
    private JPanel isiUlang = new PanelIsiUlang();
    private JPanel pengaturan = new PanelPengaturan();
    private JPanel backPanel = new JPanel();
    private Mobile view;
    
    public PanelMain(Mobile view) {
        initComponents();
        this.view = view;
        panel_konten.add(beranda);
        panel_konten.add(informasi);
        panel_konten.add(backPanel);
        panel_konten.add(transfer);
        panel_konten.add(pembayaran);
        panel_konten.add(isiUlang);
        panel_konten.add(pengaturan);
        initPanelAwal();
        getPanelBeranda().setUsername(MobileController.getInstance().getNama());
        updateJudul();
    }
    
    public void initPanelAwal() {
        beranda.setVisible(true);
        informasi.setVisible(false);
        transfer.setVisible(false);
        pembayaran.setVisible(false);
        isiUlang.setVisible(false);
        pengaturan.setVisible(false);
        backPanel.setVisible(false);
    }
    
    public PanelBeranda getPanelBeranda() {
        return (PanelBeranda) beranda;
    }
    
    public void setJudul(String text) {
        judul.setText(text);
    }
    
    public void updateJudul() {
        btn_kembali.setVisible(true);
        if (beranda.isVisible()) {
            setJudul("Beranda");
            btn_kembali.setVisible(false);
        }
        else if (informasi.isVisible()) {
            setJudul("Informasi");
        }
        else if (transfer.isVisible()) {
            setJudul("Transfer");
        }
        else if (pembayaran.isVisible()) {
            setJudul("Pembayaran");
        }
        else if (isiUlang.isVisible()) {
            setJudul("Isi Ulang");
        }
        else if (pengaturan.isVisible()) {
            setJudul("Pengaturan");
        }
    }
    
    public void gantiPanel(JPanel panel1, JPanel panel2) {
        backPanel = panel1;
        panel1.setVisible(false);
        panel2.setVisible(true);
        updateJudul();
    }

    public JPanel getBeranda() {
        return beranda;
    }

    public JPanel getInformasi() {
        return informasi;
    }

    public JPanel getTransfer() {
        return transfer;
    }

    public JPanel getPembayaran() {
        return pembayaran;
    }

    public JPanel getIsiUlang() {
        return isiUlang;
    }

    public JPanel getPengaturan() {
        return pengaturan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_header = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panel_judul = new javax.swing.JPanel();
        btn_kembali = new javax.swing.JButton();
        btn_logOut = new javax.swing.JButton();
        judul = new javax.swing.JLabel();
        panel_konten = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        panel_header.setBackground(new java.awt.Color(19, 41, 61));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PENS mobile bangking");

        javax.swing.GroupLayout panel_headerLayout = new javax.swing.GroupLayout(panel_header);
        panel_header.setLayout(panel_headerLayout);
        panel_headerLayout.setHorizontalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_headerLayout.setVerticalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panel_judul.setBackground(new java.awt.Color(0, 100, 148));
        panel_judul.setPreferredSize(new java.awt.Dimension(0, 40));

        btn_kembali.setBackground(new java.awt.Color(208, 230, 239));
        btn_kembali.setText("Kembali");
        btn_kembali.setFocusable(false);
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        btn_logOut.setBackground(new java.awt.Color(208, 230, 239));
        btn_logOut.setText("Keluar");
        btn_logOut.setFocusable(false);
        btn_logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logOutActionPerformed(evt);
            }
        });

        judul.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("Judul");

        javax.swing.GroupLayout panel_judulLayout = new javax.swing.GroupLayout(panel_judul);
        panel_judul.setLayout(panel_judulLayout);
        panel_judulLayout.setHorizontalGroup(
            panel_judulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_judulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_kembali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_logOut)
                .addContainerGap())
        );
        panel_judulLayout.setVerticalGroup(
            panel_judulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_judulLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(panel_judulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kembali)
                    .addComponent(btn_logOut)
                    .addComponent(judul)))
        );

        panel_konten.setBackground(new java.awt.Color(255, 255, 255));
        panel_konten.setPreferredSize(new java.awt.Dimension(0, 510));
        panel_konten.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_judul, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
            .addComponent(panel_konten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_konten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        beranda.setVisible(false);
        informasi.setVisible(false);
        transfer.setVisible(false);
        pembayaran.setVisible(false);
        isiUlang.setVisible(false);
        pengaturan.setVisible(false);
        backPanel.setVisible(true);
        updateJudul();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logOutActionPerformed
        // TODO add your handling code here:
        view.logOut();
    }//GEN-LAST:event_btn_logOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_logOut;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel judul;
    private javax.swing.JPanel panel_header;
    private javax.swing.JPanel panel_judul;
    private javax.swing.JPanel panel_konten;
    // End of variables declaration//GEN-END:variables
}
