/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobile.view;

import controller.TransaksiController;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import mobile.controller.MobileController;

/**
 *
 * @author Ahmad Faiz Kamaludin
 */
public class PanelIsiUlang extends javax.swing.JPanel {

    public PanelIsiUlang() {
        initComponents();
        panel_konfirmasi.setVisible(false);
        clear();
    }
    
    public void setNotifikasi(String text) {
        notifikasi.setText(text);
    }
    
    public void clear() {
        nomerIsiUlang.setText("");
        notifikasi.setText("");
        noHp.setText("");
        jumlahIsiUlang.setText("");
    }
    
    public double getNominal() {
        switch (nominalIsiUlang.getSelectedIndex()) {
            case 0: return 10000;
            case 1: return 20000;
            case 2: return 50000;
            case 3: return 100000;
            case 4: return 250000;
            case 5: return 500000;
            case 6: return 1000000;
            default: return 0;
        }
    }

    public JTextField getNomerIsiUlang() {
        return nomerIsiUlang;
    }

    public JPanel getPanel_konfirmasi() {
        return panel_konfirmasi;
    }

    public JLabel getNoHp() {
        return noHp;
    }

    public JLabel getJumlahIsiUlang() {
        return jumlahIsiUlang;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jenisIsiUlang = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        nomerIsiUlang = new javax.swing.JTextField();
        btn_bayar = new javax.swing.JButton();
        panel_konfirmasi = new javax.swing.JPanel();
        labelIsiUlang2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jumlahIsiUlang = new javax.swing.JLabel();
        noHp = new javax.swing.JLabel();
        btn_yes = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        notifikasi = new javax.swing.JLabel();
        labelIsiUlang = new javax.swing.JLabel();
        nominalIsiUlang = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(27, 152, 224));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Isi Ulang");

        jenisIsiUlang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jenisIsiUlang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLN", "Pulsa", "Go-Pay", "Ovo" }));
        jenisIsiUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisIsiUlangActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nominal");

        nomerIsiUlang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btn_bayar.setText("Bayar");
        btn_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayarActionPerformed(evt);
            }
        });

        labelIsiUlang2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelIsiUlang2.setText("ID Pelanggan");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Isi Ulang");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Nominal");

        jumlahIsiUlang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jumlahIsiUlang.setText("Rp. xxx");

        noHp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        noHp.setText("xxxx");

        btn_yes.setText("Ya");
        btn_yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yesActionPerformed(evt);
            }
        });

        btn_cancel.setText("Batal");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_konfirmasiLayout = new javax.swing.GroupLayout(panel_konfirmasi);
        panel_konfirmasi.setLayout(panel_konfirmasiLayout);
        panel_konfirmasiLayout.setHorizontalGroup(
            panel_konfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_konfirmasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_konfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(panel_konfirmasiLayout.createSequentialGroup()
                        .addGroup(panel_konfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(labelIsiUlang2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_konfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noHp)
                            .addComponent(jumlahIsiUlang))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_konfirmasiLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(btn_yes)
                .addGap(97, 97, 97)
                .addComponent(btn_cancel)
                .addGap(85, 85, 85))
        );
        panel_konfirmasiLayout.setVerticalGroup(
            panel_konfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_konfirmasiLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(panel_konfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIsiUlang2)
                    .addComponent(noHp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_konfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jumlahIsiUlang))
                .addGap(18, 18, 18)
                .addGroup(panel_konfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel)
                    .addComponent(btn_yes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        notifikasi.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        notifikasi.setForeground(new java.awt.Color(255, 255, 255));
        notifikasi.setText("Notifikasi");

        labelIsiUlang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelIsiUlang.setForeground(new java.awt.Color(255, 255, 255));
        labelIsiUlang.setText("ID Pelanggan");

        nominalIsiUlang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nominalIsiUlang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rp. 10.000,00", "Rp. 20.000,00", "Rp. 50.000,00", "Rp. 100.000,00", "Rp. 250.000,00", "Rp. 500.000,00", "Rp. 1.000.000,00" }));
        nominalIsiUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nominalIsiUlangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nominalIsiUlang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jenisIsiUlang, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomerIsiUlang, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_konfirmasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(labelIsiUlang)
                            .addComponent(notifikasi))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btn_bayar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisIsiUlang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelIsiUlang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomerIsiUlang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nominalIsiUlang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notifikasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_bayar)
                .addGap(18, 18, 18)
                .addComponent(panel_konfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        panel_konfirmasi.setVisible(false);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayarActionPerformed
        // TODO add your handling code here:
        MobileController.getInstance().isiUlang(this);
    }//GEN-LAST:event_btn_bayarActionPerformed

    private void btn_yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yesActionPerformed
        // TODO add your handling code here:
        TransaksiController.getInstance().isiUlang();
        panel_konfirmasi.setVisible(false);
        clear();
        setNotifikasi("Berhasil Isi Ulang");
        
    }//GEN-LAST:event_btn_yesActionPerformed

    private void jenisIsiUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisIsiUlangActionPerformed
        // TODO add your handling code here:
        if (jenisIsiUlang.getSelectedIndex() == 0) {
            labelIsiUlang.setText("ID Pelanggann");
            labelIsiUlang2.setText("ID Pelanggan");
        }
        else {
            labelIsiUlang.setText("No. Handphone");
            labelIsiUlang2.setText("No. HP");
        }
    }//GEN-LAST:event_jenisIsiUlangActionPerformed

    private void nominalIsiUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nominalIsiUlangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nominalIsiUlangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bayar;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_yes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> jenisIsiUlang;
    private javax.swing.JLabel jumlahIsiUlang;
    private javax.swing.JLabel labelIsiUlang;
    private javax.swing.JLabel labelIsiUlang2;
    private javax.swing.JLabel noHp;
    private javax.swing.JTextField nomerIsiUlang;
    private javax.swing.JComboBox<String> nominalIsiUlang;
    private javax.swing.JLabel notifikasi;
    private javax.swing.JPanel panel_konfirmasi;
    // End of variables declaration//GEN-END:variables
}
