/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobile.view;

import mobile.controller.*;
import mobile.view.*;

/**
 *
 * @author Ahmad Faiz Kamaludin
 */
public class PanelBeranda extends javax.swing.JPanel {

    /**
     * Creates new form PanelBeranda
     */
    private PanelMain panelMain;
    
    public PanelBeranda(PanelMain panelMain) {
        this.panelMain = panelMain;
        initComponents();
    }
    
    public void setUsername(String nama) {
        username.setText(nama);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        btn_informasi = new javax.swing.JButton();
        btn_pembayaran = new javax.swing.JButton();
        btn_isiulang = new javax.swing.JButton();
        btn_setting = new javax.swing.JButton();
        btn_transfer = new javax.swing.JButton();

        setBackground(new java.awt.Color(27, 152, 224));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selamat Datang, ");

        username.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username");

        btn_informasi.setBackground(new java.awt.Color(208, 230, 239));
        btn_informasi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_informasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user.png"))); // NOI18N
        btn_informasi.setText("Informasi");
        btn_informasi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_informasi.setFocusable(false);
        btn_informasi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_informasi.setIconTextGap(0);
        btn_informasi.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_informasi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_informasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_informasiActionPerformed(evt);
            }
        });

        btn_pembayaran.setBackground(new java.awt.Color(208, 230, 239));
        btn_pembayaran.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_pembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/mobile/payment.png"))); // NOI18N
        btn_pembayaran.setText("Pembayaran");
        btn_pembayaran.setFocusable(false);
        btn_pembayaran.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pembayaran.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_pembayaran.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pembayaranActionPerformed(evt);
            }
        });

        btn_isiulang.setBackground(new java.awt.Color(208, 230, 239));
        btn_isiulang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_isiulang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/mobile/isiUlang.png"))); // NOI18N
        btn_isiulang.setText("Isi Ulang");
        btn_isiulang.setFocusable(false);
        btn_isiulang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_isiulang.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_isiulang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_isiulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_isiulangActionPerformed(evt);
            }
        });

        btn_setting.setBackground(new java.awt.Color(208, 230, 239));
        btn_setting.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/mobile/settings.png"))); // NOI18N
        btn_setting.setText("Pengaturan");
        btn_setting.setFocusable(false);
        btn_setting.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_setting.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_setting.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_settingActionPerformed(evt);
            }
        });

        btn_transfer.setBackground(new java.awt.Color(208, 230, 239));
        btn_transfer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_transfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/mobile/transfer.png"))); // NOI18N
        btn_transfer.setText("Transfer");
        btn_transfer.setFocusable(false);
        btn_transfer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_transfer.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_transfer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transferActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(btn_isiulang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_informasi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(btn_transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btn_setting, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(104, 104, 104)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(username)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_transfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_informasi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_isiulang, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btn_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(btn_setting, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_informasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_informasiActionPerformed
        // TODO add your handling code here:
        panelMain.gantiPanel(this, panelMain.getInformasi());
        MobileController.getInstance().updatePanelInformasi((PanelInformasi) panelMain.getInformasi());
        MobileController.getInstance().updateSaldo((PanelInformasi) panelMain.getInformasi());
    }//GEN-LAST:event_btn_informasiActionPerformed

    private void btn_transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transferActionPerformed
        // TODO add your handling code here:
        panelMain.gantiPanel(this, panelMain.getTransfer());
    }//GEN-LAST:event_btn_transferActionPerformed

    private void btn_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pembayaranActionPerformed
        // TODO add your handling code here:
        panelMain.gantiPanel(this, panelMain.getPembayaran());
    }//GEN-LAST:event_btn_pembayaranActionPerformed

    private void btn_isiulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_isiulangActionPerformed
        // TODO add your handling code here:
        panelMain.gantiPanel(this, panelMain.getIsiUlang());
    }//GEN-LAST:event_btn_isiulangActionPerformed

    private void btn_settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_settingActionPerformed
        // TODO add your handling code here:
        panelMain.gantiPanel(this, panelMain.getPengaturan());
    }//GEN-LAST:event_btn_settingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_informasi;
    private javax.swing.JButton btn_isiulang;
    private javax.swing.JButton btn_pembayaran;
    private javax.swing.JButton btn_setting;
    private javax.swing.JButton btn_transfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
