/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobile.view;

import controller.NasabahController;

/**
 *
 * @author Ahmad Faiz Kamaludin
 */
public class PanelPengaturan extends javax.swing.JPanel {

    /**
     * Creates new form PanelBeranda
     */
    public PanelPengaturan() {
        initComponents();
        panelGantiUserId.setVisible(false);
        panelGantiPassword.setVisible(false);
        clearUserId();
        clearPassword();
        clearNotifikasi();
    }
    
    public void clearUserId() {
        userId_lama.setText("");
        userId_baru.setText("");
        userId_password.setText("");
    }
    
    public void clearPassword() {
        password_lama.setText("");
        password_baru.setText("");
        password_konfirmasi.setText("");
    }
    
    public void clearNotifikasi() {
        userId_notifikasi.setText("");
        password_notifikasi.setText("");
    }
    
    public void setNotifikasiUserId(String text) {
        userId_notifikasi.setText(text);
    }
    
    public void setNotifikasiPassword(String text) {
        password_notifikasi.setText(text);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_userId = new javax.swing.JButton();
        btn_password = new javax.swing.JButton();
        panelGantiUserId = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userId_lama = new javax.swing.JTextField();
        userId_baru = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        userId_password = new javax.swing.JPasswordField();
        btn_changeUserId = new javax.swing.JButton();
        btn_cancelUserId = new javax.swing.JButton();
        panelGantiPassword = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        password_lama = new javax.swing.JPasswordField();
        password_baru = new javax.swing.JPasswordField();
        password_konfirmasi = new javax.swing.JPasswordField();
        btn_changePassword = new javax.swing.JButton();
        btn_cancelPassword = new javax.swing.JButton();
        userId_notifikasi = new javax.swing.JLabel();
        password_notifikasi = new javax.swing.JLabel();

        setBackground(new java.awt.Color(27, 152, 224));

        btn_userId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_userId.setText("Ganti User ID");
        btn_userId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userIdActionPerformed(evt);
            }
        });

        btn_password.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_password.setText("Ganti Password");
        btn_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_passwordActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("User ID lama");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("User ID baru");

        userId_lama.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        userId_baru.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Password");

        userId_password.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btn_changeUserId.setText("Ganti");
        btn_changeUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changeUserIdActionPerformed(evt);
            }
        });

        btn_cancelUserId.setText("Batal");
        btn_cancelUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelUserIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGantiUserIdLayout = new javax.swing.GroupLayout(panelGantiUserId);
        panelGantiUserId.setLayout(panelGantiUserIdLayout);
        panelGantiUserIdLayout.setHorizontalGroup(
            panelGantiUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGantiUserIdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGantiUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGantiUserIdLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userId_lama))
                    .addGroup(panelGantiUserIdLayout.createSequentialGroup()
                        .addGroup(panelGantiUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGantiUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userId_baru)
                            .addComponent(userId_password))))
                .addContainerGap())
            .addGroup(panelGantiUserIdLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btn_changeUserId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancelUserId)
                .addGap(81, 81, 81))
        );
        panelGantiUserIdLayout.setVerticalGroup(
            panelGantiUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGantiUserIdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGantiUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userId_lama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGantiUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userId_baru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGantiUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userId_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGantiUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_changeUserId)
                    .addComponent(btn_cancelUserId))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Password lama");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Password baru");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Password baru");

        password_lama.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        password_baru.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        password_konfirmasi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btn_changePassword.setText("Ganti");
        btn_changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changePasswordActionPerformed(evt);
            }
        });

        btn_cancelPassword.setText("Batal");
        btn_cancelPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGantiPasswordLayout = new javax.swing.GroupLayout(panelGantiPassword);
        panelGantiPassword.setLayout(panelGantiPasswordLayout);
        panelGantiPasswordLayout.setHorizontalGroup(
            panelGantiPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGantiPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGantiPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGantiPasswordLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(password_lama))
                    .addGroup(panelGantiPasswordLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(password_konfirmasi))
                    .addGroup(panelGantiPasswordLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(password_baru)))
                .addContainerGap())
            .addGroup(panelGantiPasswordLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btn_changePassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(btn_cancelPassword)
                .addGap(83, 83, 83))
        );
        panelGantiPasswordLayout.setVerticalGroup(
            panelGantiPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGantiPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGantiPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(password_lama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGantiPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(password_baru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGantiPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(password_konfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGantiPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_changePassword)
                    .addComponent(btn_cancelPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userId_notifikasi.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        userId_notifikasi.setForeground(new java.awt.Color(255, 255, 255));
        userId_notifikasi.setText("Notifikasi");

        password_notifikasi.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        password_notifikasi.setForeground(new java.awt.Color(255, 255, 255));
        password_notifikasi.setText("Notifikasi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGantiUserId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGantiPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_userId, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_password)
                            .addComponent(userId_notifikasi)
                            .addComponent(password_notifikasi))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_userId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGantiUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userId_notifikasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGantiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_notifikasi)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelUserIdActionPerformed
        // TODO add your handling code here:
        panelGantiUserId.setVisible(false);
    }//GEN-LAST:event_btn_cancelUserIdActionPerformed

    private void btn_userIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userIdActionPerformed
        // TODO add your handling code here:
        panelGantiUserId.setVisible(true);
    }//GEN-LAST:event_btn_userIdActionPerformed

    private void btn_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_passwordActionPerformed
        // TODO add your handling code here:
        panelGantiPassword.setVisible(true);
    }//GEN-LAST:event_btn_passwordActionPerformed

    private void btn_cancelPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelPasswordActionPerformed
        // TODO add your handling code here:
        panelGantiPassword.setVisible(false);
    }//GEN-LAST:event_btn_cancelPasswordActionPerformed

    private void btn_changeUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changeUserIdActionPerformed
        // TODO add your handling code here:
        if (!(userId_lama.getText().isEmpty() || userId_baru.getText().isEmpty() || userId_password.getText().isEmpty())) {
            if (NasabahController.getInstance().isValidUserId(userId_lama.getText())) {
                if (NasabahController.getInstance().isValidPassword(userId_password.getText())) {
                    NasabahController.getInstance().changeUserId(userId_baru.getText());
                    panelGantiUserId.setVisible(false);
                    setNotifikasiUserId("User ID berhasil diganti");
                    clearUserId();
                }
                else
                    setNotifikasiUserId("Password anda salah");
            }
            else
                setNotifikasiUserId("User ID lama anda salah");
        }
        else
            setNotifikasiUserId("Tolong isi semua field nya");
    }//GEN-LAST:event_btn_changeUserIdActionPerformed

    private void btn_changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changePasswordActionPerformed
        // TODO add your handling code here:
        if (!(password_lama.getText().isEmpty() || password_baru.getText().isEmpty() || password_konfirmasi.getText().isEmpty())) {
            if (NasabahController.getInstance().isValidPassword(password_lama.getText())) {
                if (password_baru.getText().equals(password_konfirmasi.getText())) {
                    NasabahController.getInstance().changePassword(password_baru.getText());
                    panelGantiPassword.setVisible(false);
                    setNotifikasiPassword("Password anda berhasil diubah");
                    clearPassword();
                }
                else
                    setNotifikasiPassword("Password baru anda tidak cocok");
            }
            else
                setNotifikasiPassword("Password lama anda salah");
        }
        else
            setNotifikasiPassword("Tolong isi semua fieldnya");
    }//GEN-LAST:event_btn_changePasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelPassword;
    private javax.swing.JButton btn_cancelUserId;
    private javax.swing.JButton btn_changePassword;
    private javax.swing.JButton btn_changeUserId;
    private javax.swing.JButton btn_password;
    private javax.swing.JButton btn_userId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelGantiPassword;
    private javax.swing.JPanel panelGantiUserId;
    private javax.swing.JPasswordField password_baru;
    private javax.swing.JPasswordField password_konfirmasi;
    private javax.swing.JPasswordField password_lama;
    private javax.swing.JLabel password_notifikasi;
    private javax.swing.JTextField userId_baru;
    private javax.swing.JTextField userId_lama;
    private javax.swing.JLabel userId_notifikasi;
    private javax.swing.JPasswordField userId_password;
    // End of variables declaration//GEN-END:variables
}
